### PR TITLE
HAPROXY: Version 2.3.x supports Syslog Protocol (UDP/TCP)

### PR DESCRIPTION
**Pull request by erwindwight**
We have a use case to migrate our central Syslog servers to be behind haproxy, and we need TCP and UDP backend, so haproxy version 2.3 will help us with our use case.

https://www.haproxy.com/blog/announcing-haproxy-2-3/#syslog-protocol-udp-tcp
https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#3.10

### CODE REVIEW

**Comment by daianamezdrea** [comment]
Hi @erwindwight, just some minor rubocop offenses, do you mind if I fix them and push the changes to your PR? Or you can do it if you want

**Review by erwindwight — COMMENTED** [review]
@daianamezdrea thank you for the fix.
Didn't have time to work on it earlier, so thanks!

**Comment by daianamezdrea** [comment]
Hello @erwindwight, can you add some tests here to provide the functionality ? Thank you and let me know when is ready to be merged, also if you need help or examples I'm here to help. Cheers !

**Comment by anthonysomerset** [comment]
i also have a use case for this :) would love to know how i can help with reviewing this and getting it merged

**Comment by anthonysomerset** [comment]
i can confirm this is working fine for me

**Comment by erwindwight** [comment]
> I can confirm this is working fine for me

Hi @anthonysomerset 
Thank you for taking the time to check this out.
We have had this working internally in our organization for some time.

This is pending proper unit testing, this is in my task list, but I can't find time to work on this.
Feel free to help on this part, and I would love to see this merge.

**Pull request closed without merging**
