### PR TITLE
mange_config_dir parameter

### PR DESCRIPTION
**Pull request by posteingang**
make $haproxy::manage_config_dir useable in config.pp

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @posteingang currently this change results in test failures. 
If you could address this I will work on getting your change merged.

**Comment by hunner** [comment]
The base class is just a thin wrapper around a default declaration of `haproxy::instance` which is where the real interface is. The way to make this change would be to add a `manage_config_dir` parameter to `haproxy::instance` and then also pass that through to the `haproxy::config` resource declared by `haproxy::instance`. That's why the tests are failing.

**Comment by david22swan** [comment]
@posteingang Is there any movement on this PR?

**Comment by posteingang** [comment]
@david22swan Sry, for the late response. At the moment I have not enough time to fix the tests. Unfortunately I am not a create dev so maybe someone else can help?

**Comment by david22swan** [comment]
@posteingang Apologies but I am unsure if there any any within the team that have the time to work on this as we have been rather busy over the last few months. If you yourself do not have the time to finish this then it may be best to open up a ticket detailing what you have done, and had planned to do and submit it to be appraised. If it is accepted it will then be put on our backlog of work to be completed at a later time.

**Comment by david22swan** [comment]
@posteingang Apologies but due to the length of time that this has lain fallow without anyone taking it up I am know closing this PR. I apologize, and if in the future you choose to submit once again, we will happily review it.
Best Wishes

**Pull request closed without merging**
