### PR TITLE
Add check of OS for the systemd unitfile

### PR DESCRIPTION
**Pull request by surprisingb**
As the [systemd.unit man page states on a Debian based OS](https://manpages.debian.org/stretch/systemd/systemd.unit.5.en.html), 
the unit files should be put in /lib/systemd/system  instead of /usr/lib/systemd/system, otherwise the module fails on Debian.

### CODE REVIEW

**Comment by lionce** [comment]
Hello @surprisingb ,

Thank your for your contribution. It looks like the unit tests are failing because of trailing whitespace error. 
```
manifests/instance_service.pp - ERROR: trailing whitespace found on line 102
manifests/instance_service.pp - ERROR: trailing whitespace found on line 104
manifests/instance_service.pp - ERROR: trailing whitespace found on line 106
```
In order to merge your PR, please fix the errors.

**Comment by surprisingb** [comment]
Hi @lionce,
sorry for the late reply. I removed the trailing whitespaces, the unit tests should be ok now.
Thanks

**Comment by lionce** [comment]
Hello @surprisingb ,

I ran the acceptance tests through all our testing platforms and they are failing for redhat5, centos5, oracle5 and oracle6 with the same error when it's trying to run the following command: /usr/bin/yum -d 0 -e 0 -y install socat
M2Crypto.SSL.SSLError: tlsv1 alert protocol version

Cheers!

**Comment by surprisingb** [comment]
I don't get how is this related to my changes, am I missing something?

**Comment by carabasdaniel** [comment]
Hi @surprisingb,

The tests were failing because the branch you are on is ~40 commits behind the current master, but these commits seem to pass on the latest master. 
Thank you for your contribution.

**Pull request merged**
