### PR TITLE
defaults section overhaul - adding support of named defaults in other sections

### PR DESCRIPTION
**Pull request by jardleex**
Hi there,

this request attempts to overhaul the defaults section handling.
Since HAProxy 2.4 it's possible to inherit a named default section on frontend/backend/listen sections. This makes it unnecessary to put frontend/backend/listen section right behind such a named default block.
An example can be found in the HAProxy blog post [Announcing HAProxy 2.4](https://www.haproxy.com/de/blog/announcing-haproxy-2-4/) below the headline *Named Defaults*.

While implementing this option I stumbled over two things to discuss:

1) How's about removing the `$defaults_options` from params.pp? The defaults set there are round about 10 years old. HAProxy has greatly evolved over time and starts with sane defaults I'd say. It's not even required to provide any `defaults` section anymore to start HAProxy.
Removing `$defaults_options` would also remove the need of merging the hash with a user provided one.
2) The way HAProxy requires the named defaults to be ordered is contrary to the ordering behavior of `concat::fragment`. In order to inherit a named default in HAProxy it needs to be place above the first inheritance. Otherwise HAProxy complains it can't find it.
   `concat::fragment` [orders](https://github.com/puppetlabs/puppetlabs-concat/blob/v7.2.0/manifests/fragment.pp#L8-L10) fragments with the same order number alphabetical. As all defaults have the order 12 it will order them alphabetical, not in the order provided by manifest oder Hiera. This leads to a un-loadable config for HAProxy.
   To bypass this I did this in my tests:
    ```puppet
    my_module::defaults:
      10_de_mydefault:
        defaults_options:
          maxconn: 1024
          mode: http
          balance: roundrobin
          default-server:
            - 'check'
            - 'init-addr last,libc,none'
            - 'inter 10s'
            - 'slowstart 2m'
      de_http from 10_de_mydefault:
        defaults_options:
          option:
            - 'forwardfor except 127.0.0.1'
      de_tcp from 10_de_mydefault:
        defaults_options:
          mode: 'tcp'
    ```
    The "first to be" section has been prefixed with an integer to overcome the `concat::fragment` default sorting. Does anybody got a better idea?

Please let me know what you think and what can be improved on this request.

### CODE REVIEW

**Comment by jordanbreen28** [comment]
Closed and re-opened to re-kick automated testing.

**Comment by jordanbreen28** [comment]
Hi @jardleex - thank you for taking the time to open this PR; unfortunately there seems to be test failures, can you look to resolve these and then rebase this PR with the current main?
Thanks

**Comment by jardleex** [comment]
Hi @jordanbreen28,

I'm aware that some tests are broken. I just did not start fixing them due to the open discussions from my initial post as their outcome will change the PR as a whole an such the related tests.
My initial idea was to get some feedback here about the idea change and find a answers to my uncertain points.

**Comment by GSPatton** [comment]
Hi @jardleex. This is a tricky PR to review since it is large in scope, has open questions and has many failing tests. I would suggest breaking this PR into smaller PRs, perhaps based on the two points you discuss in the description. As regards to feedback, I would suggest asking in Puppet's [community Slack](https://puppetcommunity.slack.com/archives/C0W298S9G). Thank you for your contribution. We look forward to seeing what you come up with.

**Pull request closed without merging**
