### PR TITLE
Add support for managing map files

### PR DESCRIPTION
**Pull request by antaflos**
Add a defined type haproxy::mapfile to manage map files as documented in
https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#7.3.1-map

A map file contains one key + value pair per line. These mappings are
modelled in a `mappings` array, whose elements may either be Hashes with
a single key-value pair each or simple Strings.

Contains updated documentation and spec tests for the new defined type.

### CODE REVIEW

**Comment by antaflos** [comment]
The spec tests are quite basic so I am open to suggestions on extending them.

**Comment by tphoney** [comment]
The work looks good to me, we will get it reviewed at our community meeting. :+1:

**Comment by antaflos** [comment]
I have just now rebased the branch.

**Comment by antaflos** [comment]
Ugh, I need to update this change and take into consideration the newly merged multi-instance stuff. Will do that when I get back from vacation next week (this hotel's wifi is not great anyway).

**Comment by igalic** [comment]
@antaflos ping

**Comment by nibalizer** [comment]
@antaflos any chance you can circle back to this?

**Comment by antaflos** [comment]
Yes, I'm on it now.

**Comment by antaflos** [comment]
This should work now and be good to merge. I believe I have found a few bugs owed to the huge change that was multi-instance support, and I am not completely sure that the new `haproxy::mapfile` type will work correctly with multiple instances. I couldn't even get multiple instances to run on my Vagrant development system.

**Comment by antaflos** [comment]
@nibalizer @tphoney please don't forget about this :)

**Pull request merged**
