### PR TITLE
Don't hardcode haproxy binary paths

### PR DESCRIPTION
**Pull request by robbat2**
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

### CODE REVIEW

**Comment by tphoney** [comment]
@robbat2 This looks like a good change, but the tests are failing. Could you please have a look.

**Comment by ctiml** [comment]
@robbat2 Thank you. I need this change.

**Comment by tphoney** [comment]
Hi @robbat2 , thanks for the work you have put into this pull request. However due to inactivity and failing unit tests this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

I looked to see if there were any quick fixes for the tests, but it looks as if there will need to be some significant changes to make this work.

**Comment by robbat2** [comment]
Thanks github for not notifying me about comments here before.

I'm wondering why `$haproxy_bin = $haproxy::haproxy_bin,` in the haproxy::instance_service definition doesn't work, but `$merge_options = $haproxy::merge_options` in `haproxy::config` does.

**Pull request closed without merging**
