### PR TITLE
Adding mode to backend class

### PR DESCRIPTION
**Pull request by hundredacres**
Adding mode parameter to backend class

### CODE REVIEW

**Comment by HelenCampbell** [comment]
Hey @hundredacres , Thank you for your pull request. With the addition of a new parameter docs will need to be updated.

**Comment by nibalizer** [comment]
@HelenCampbell can you rebase this?

**Comment by hundredacres** [comment]
How should I do the rebase? A little fuzzy on that point.

**Comment by hundredacres** [comment]
Ok, think I got the rebase done.

**Comment by nibalizer** [comment]
@hundredacres unfortunately no, the rebase was not done correctly. You want the tip of master + your commit: 3c3a4d4be0ecdceca923eb2ef3dd68f972077e51

I would probably create a new branch off of master (make sure you have upstream's master) and `git cherry-pick 3c3a4d4be0ecdceca923eb2ef3dd68f972077e51`.

**Comment by DavidS** [comment]
re-uploaded as #211, closing this.

**Pull request closed without merging**
