### PR TITLE
(WIP) Use consul-tempalte for balancemembers

### PR DESCRIPTION
**Pull request by bodepd**
This patch adds a second type of resource for
adding balancemembers, namely: haproxy/balancemember_consul.

These balance members use consul-tempalte as a replacement for
export resources and assume that both consul as well as
consul-template are installed on any systems using this
defined resource type.

Consul-template offers an alternative to exported resources
that allows for much more dynamic updates to configuration
based on the current state of a load balanced service (it
can allow nearly instantaneous updates of config when pool members
or added, removed, or start behaving badly)

Puppet configures the consul templates which rely on consul-template
to actually convert them into the real haproxy file on disk.

NOTE: this is marked as A WIP b/c I am interesting in feedback
regarding if this patch is something that people or puppetlabs
is interested in. I am happy to add tests or whatever other
requirements might exist once I have that feedback.

### CODE REVIEW

**Comment by bodepd** [comment]
I was confused as to what branch to base this on, I can't base it on master until #197 is merged.

**Comment by igalic** [comment]
@bodepd now that #197 is merged as #199, could you extend this PR with documentation in the README?

**Comment by bodepd** [comment]
@igalic sure. I can rebase and extend docs.

**Comment by traylenator** [comment]
Might a more flexible  way to achieve the same thing be a for the *haproxy::backend* to support a
*custom_fragment* like  *haproxy::init* already does. 

So something like

```puppet
$consul_magic = @(END)
{{range service "foo"}}
server {{.ID}} {{.Address}}:{{.Port}} <% if @define_cookies %><%= " cookie " %>{{.Name}}<% end %> check %>
{{end}}
END


haproxy::listen{'foo':
  ipaddress             => ['1.2.3.4','5.6.7.8']
  server_names      => ['a.example.org','b.example.org']
  custom_fragment => $consul_magic
}
```

This could be used for consul but probably 100 other things also.

**Comment by tphoney** [comment]
@bodepd just pinging you. In case you have forgotten about this.

**Comment by mentat** [comment]
Ping.

**Comment by bodepd** [comment]
sorry @tphoney @mentat, I'll add some docs and do a rebase this week.

**Comment by tphoney** [comment]
Thanks for the continued effort :) 
apologies if it sounds like we are hounding you.

**Comment by bodepd** [comment]
I didn't see a way to update what branch this was submitted against, so I opened a new PR #221

**Pull request closed without merging**
